---
title: "Choose_Function_Final"
author: "Dan Brooks"
date: "November 1, 2015"
output: pdf_document
---


```{r}
#Assignment 2
#Dan Brooks
#This program will be used to calculate the choose function (xCy). It taked the total population "x" and
#picks a subpopulation "y" from that population. It them calculates how many possible combinations are
#there for picking "y" objects from "x" total objects (order doesn't matter)



#factorial function will take one parameter being passed to it and returns an integer value
     #This function will calculate the fatorial (!) of the value that is passed to it
          #factorial is defined as: n! = n*(n-1)*(n-2)....*(2)*(1)
     #It initialzes the solution to 1 (fact)
     #It takes the soultion and multiplies it by the number that was passed into the function (x)
     #Then we subtract 1 from the number being passed into the function
     #The process is repeated until x is one (we do not need to multiply by one because it doesn't change the answer)
factorial <- function(x)
{
  fact <- 1
  while (x > 1)
  {
    fact <- fact * x
    x <- x - 1
  }
  
  return(fact)
}

#Diffactorial function will take two parameters being passed to it and returns an integer value
     #This function will calculate the fatorial (!) of the difference of the two values passed to it
          #Factorial is defined as: n! = n*(n-1)*(n-2)....*(2)*(1)
     #Take the differnece of the two values that are passed to it (diff)
     #It initialzes the solution to 1 (fact)
     #It takes the soultion and multiplies it by the number that was passed into the function (x)
     #Then we subtract 1 from the number being passed into the function
     #The process is repeated until x is one (we do not need to multiply by one because it doesn't change the answer)
Diffactorial <- function(x, y)
{
  diff <- (x-y)
  fact <- 1
  while (diff > 1)
  {
    fact <- fact * diff
    diff <- diff - 1
  }
  
  return(fact)
}
  
#Choose function will take in two parameters being pased to it and calculate the combination of the two numbers
     #The function will calculate the combination of the two numbers that were inputed from the user
     #It will take the factorial of the population (factorial(x)) and divide it by the factorial of the 
          #difference of the population and the number of choices (Diffactorial(x,y)) times the factorial
          #of the number of choices (factorial(y)).
     #It will give the answer for the total number of combinations for the number of choices out of a given 
     #population.
     #There is error checking to make sure that the input the user places into the function will be valid.
          #If the population (x) is less then the number of items that you are choosing (y) the output 
          #will be zero because.
          #If (x) is greater than 0 and (y) is equal 0 then the output will be 1 because choosing no objects out
          #a population means that their is still the population, just one choice.
          #If (x) and (y) are the same then the output will be one because there is ony one way to pick (y) items 
          #out of a population of (x) items if they are the same.
Choosefinal <- function (x, y)
{
  if (x < y)
  {
    print (0)
  }
  else 
  {
    if (x > 0 && y == 0)
    {
      print(1)
    }
    else
    {
      if (x == y)
      {
        print (1)
      }
      else
      {
        factorial(x)/(Diffactorial(x,y)*factorial(y))
      }
    }
  }
}
```

```{r}
#Here are the test scenarios that I created for my function that I made. I compared it to the R function that
#already exists within Rstudio to make sure that my results were all correct.
#I placed in some error checking within my code that will allow me deal with a wide array of possible input.
#My function is the Choosefinal function and the R delivered function is the choose function.
#The answers to the functions are below the function calls:
Choosefinal(0,0)
1
choose(0,0)
1
Choosefinal(0,10)
0
choose(0,10)
0
Choosefinal(1,10)
0
choose(1,10)
0
Choosefinal(10,0)
1
choose(10,0)
1
Choosefinal(10,10)
1
choose(10,10)
1
Choosefinal(44,19)
1.408831e+12
choose(44,19)
1.408831e+12
```
